### ISSUE TITLE
Disable gzip on msie6, which does not support gzip?

### ISSUE THREAD

**Issue by amilajack** [h5bp/server-configs-nginx#125]

**Comment by Rowno** [comment]
http://www.ie6death.com/

**Comment by hvelarde** [comment]
we are in 2015; Internet Explorer 6 represents 0.1% of IE traffic... can we just move on?

https://www.w3counter.com/trends

**Comment by alrra** [comment]
@amilajack Thanks for bringing this up, but I'm going to close this issue because:

* Internet Explorer 6 does support `gzip`
* There were some bugs in early **unpatched** versions of [Internet Explorer 5.5](https://support.microsoft.com/en-us/kb/313712) and [Internet Explorer 6 SP1](https://support.microsoft.com/en-us/kb/312496) (again SP1!!), but those versions are pretty much non-existing today
