### ISSUE TITLE
Multiple SSL vhosts config issue

### ISSUE THREAD

**Issue by pentago** [h5bp/server-configs-nginx#164]
What I think should be changed is to remove SSL key/cert lines from ssl.conf (and move to ssl.example.com) as its wrong to share same ones through multiple vhosts (in  case common  behavior is duplication of example vhosts config). 

Thoughts?

**Comment by Zumochi** [comment]
I do the same. Have a default ssl.conf in conf.d with all SSL settings except listen and ssl_certificate, those two I put per vhost configuration file.

**Comment by quantumpacket** [comment]
100% agree, was never sure why it was done the way it currently is. If we have more consensus I'll send a PR.

**Comment by AD7six** [comment]
Not sure I understand.

The entries in ssl.conf are [comments only](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf#L42-L45) - and as indicated by the comments are there for when a client doesn't support SNI.

Moreover, if a server block declares its own ssl certs - the ones in ssl.conf _if uncommented_ don't apply.

?

**Comment by Zumochi** [comment]
I think the difference is that for SSL virtual hosts we now explicitly include the configuration (as shown [here](https://github.com/h5bp/server-configs-nginx/blob/master/sites-available/ssl.example.com#L23)), instead of simply putting it in a global `include conf.d/*.conf`. Then again explicit is better than implicit :)

This would also mean having to move the `add_header` directives in that file somewhere else... I think we can probably keep it this way.

**Comment by LeoColomb** [comment]
Done via #204, which should allow more flexibility.
