### ISSUE TITLE
Fast CGI Configs

### ISSUE THREAD

**Issue by designermonkey** [h5bp/server-configs-nginx#85]
I love this resource and it's really helped a couple of large client servers, but I feel one tiny thing is missing: fastcgi config.

Any chance of adding some defaults for fastgci setups?

**Comment by AD7six** [comment]
> For example have a directive only for php fpm using a unix socket, and one for using a tcp socket.

That would be an ever expanding list of permutations, that _I_ would be left maintaining. This repo, as with all server config repos (with the obvious exception of the iis repo),  is intended to be scripting-language agnostic, rather than all-inclusive.

The config snippets are intended to be used as-is; if the config snippet needs editing to be used it is of limited use IMO, and that's where it should be [documented](https://github.com/h5bp/server-configs-nginx/tree/master/doc) rather than available for include. However, I really don't want to go in the direction of "Know nothing at all about nginx? This is the only source of info you need to read" users _should_ have a base understanding of nginx and be referring to other (official) sources of information where the scope of what they need leaves the scope of this repo.

So I think I'll pass =) but thanks for the suggestion!

**Comment by designermonkey** [comment]
no probs.
